### ISSUE TITLE
Main differences to wasmcloud?

### ISSUE THREAD

**Issue by matsbror** [madflojo/tarmac#29]
Interesting project! What would you say are you main differentiating points compared to [wasmcloud](https://wasmcloud.dev/)?

**Comment by madflojo** [comment]
Great question.

I think the crux of it can be summarized in:

From my understanding, wasmcloud is aiming to run multiple WASM projects across a singular platform. Where as Tarmac is built to run a single WASM project. The difference being wasmcloud is trying to be a Kubernetes meets JBoss for WASM. Where Tarmac is trying to be more like an Apache Tomcat for WASM.

The goal of Tarmac is to run a single function quickly and easily while also providing the ability to integrate with dependencies. There are other projects out there that let you run WASM code as an HTTP endpoint but don't bring the dependencies integrations.

There are some other more items that make a difference between Tarmac and wasmcloud.

* wasmcloud is far more active with a bigger community
* wasmcloud has SDK's for interacting with dependencies where Tarmac is exposing waPC to the user. This is a pro for wasmcloud.
* Both are trying to make developing wasm based services simple, while also providing the ability to integrate with services such as DB's, Caches, etc.

**Comment by madflojo** [comment]
Another factor that I forgot to mention in my initial reply is that Tarmac can be used to add WASM hosting capabilities to other services.

https://tarmac.gitbook.io/tarmac/developer-resources/toolkit

This would be a useful way for existing services written in Go to add WASM extensions.

**Comment by madflojo** [comment]
Hopefully, this answer was what you were looking for. I am going to close this for now.
