### ISSUE TITLE
 GGO free wasm runner

### ISSUE THREAD

**Issue by gedw99** [madflojo/tarmac#30]
Wazero is faster than the others due to less overhead 

https://wazero.io/

It can run within envoy or alone 
Config can be file based or off envoy.

It can also run wasi and wasm compiled golang .

**Comment by gedw99** [comment]
I just realised you can use it anyway via: https://github.com/wapc/wapc-go/blob/master/engines/wazero/wazero.go

:)

**Comment by madflojo** [comment]
Thanks @gedw99, I'll look at updating wapc and switching.
